#!/bin/sh
set -eu
exec op-proposer \
  --poll-interval=10s \
  --rpc.port=8560 \
  --rollup-rpc=http://op-node:8547 \
  --l2oo-address=0x12DA5fb5483A64755a625aa220cB0Ac8d4ff1935 \
  --private-key=$GS_PROPOSER_PRIVATE_KEY \
  --l1-eth-rpc=$L1_RPC_URL
