#!/bin/sh
set -eu
exec op-node --l2=http://op-geth:8551 \
  --l2.jwt-secret=/config/jwt.txt \
  --sequencer.enabled \
  --sequencer.l1-confs=5 \
  --verifier.l1-confs=4 \
  --rollup.config=/config/rollup.json \
  --rpc.addr=0.0.0.0 \
  --rpc.port=8547 \
  --p2p.disable \
  --rpc.enable-admin \
  --p2p.sequencer.key=$GS_SEQUENCER_PRIVATE_KEY \
  --l1=$L1_RPC_URL \
  --l1.rpckind=$L1_RPC_KIND \
  --l1.beacon=$L1_BEACON_URL \
  --l1.beacon-archiver=$L1_BEACON_URL \
  --plasma.enabled="false" \
#  --plasma.da-server=http://da-server:3100
#  --plasma.da-service="true" \
#  --plasma.da-server=https://dcda-dev.dome.cloud

